version: '3.8'
services:
  postgres:
    image: postgres:14.12
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gsfanatic
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: